---
- name: Add MongoDB apt key
  apt_key: keyserver=keyserver.ubuntu.com id=EA312927

- name: add MongoDB repository
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/3.2 multiverse' state=present filename='mongodb'

- name: Update APT Cache
  apt: update_cache=yes

- name: Install MongoDB
  apt: pkg=mongodb-org state=present
  