---
- name: Check if MongoDB Key is present
  stat: path=/root/.mongodb-3.2.asc
  register: mongodb_key_downloaded

- name: Download MongoDB key
  shell: "/usr/bin/curl -O /root/.mongodb-3.2.asc https://www.mongodb.org/static/pgp/server-3.2.asc"
  when: mongodb_key_downloaded.stat.exists == false

- name: add MongoDB apt key
  apt_key: file=/root/.mongodb-3.2.asc state=present

- name: add MongoDB repository
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/3.2 main' state=present filename='mongodb'

- name: Update APT Cache
  apt: update_cache=yes

- name: Install MongoDB
  apt: pkg=mongodb-org state=present
  